senior_track/senior_track/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('track.urls')),
]

senior_track/track/urls.py
from django.urls import path

from . import views


app_name = 'base'

urlpatterns = [
    path('', views.home, name='home'),
    path('update/', views.update, name='update'),
    path('map/', views.map, name = 'map')
]

senior_track/track/models.py
from django.db import models

# Create your models here.

senior_track/track/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
import json
from django.conf import settings

from .scripts import mqttapi
from .scripts import sms


_GRANNY_DATA = './track/conf/granny_data.json'

# Callback function to mqtt object
def test(device_id):
    with open(_GRANNY_DATA) as json_obj:
        data = json.load(json_obj)

        if device_id in data['id']:
            sms.alarm((data['id'][device_id] + ' had a bad fall'))
            print(data['id'][device_id], ' had a bad fall')

# Creates an mqtt object and setts a callback function
m = mqttapi.MQTT(host='10.101.115.207', port=1883, topics=['tagsLive'], use_ssl = False, use_websocket = False)
m.set_fall_callback(test)

# Create your views here.
def home(request):
    return render(request, 'track/index.html')

def update(request):
    with open(_GRANNY_DATA) as json_obj:
        data = json.load(json_obj)
        
        # Getts granny update
        granny_update = []
        for granny_id in data['id']:
            granny_update.append({data['id'][granny_id]:{
                    'coord':m.get_coordinates(granny_id),
                    'status':m.fell_recently(granny_id)
                }})
                

        # Check if granny out of range
        if granny_update[2]['Reidar']['coord']['y'] < 474 and not settings.RAN:
            print(granny_update)
            settings.RAN = True
            sms.alarm('Reidar ran away ')
            

    return JsonResponse(granny_update, safe=False)
    
def map(request):
    return render(request, 'map/map.html')
    

senior_track/track/templates/map/map.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css" />
	<script src="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>

    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.js' %}"></script>

	<style>
		.leaflet-container {
			margin-left: auto;
			margin-right: auto;
			margin-top: auto;
			margin-bottom: auto;
			height: 100%;
			width: 100%;
			padding: 475px 475px 475px 475px;
		}

		.body-main {
			height: 100%;
			width: 100%;
		}
	</style>

</head>

<body>
	<div class="leaflet-container" id="map"></div>

	<!-- <script src="../node_modules/simpleheat/simpleheat.js"></script>
	<script src="../src/HeatLayer.js"></script> -->

	<!--<script src="http://leaflet.github.io/Leaflet.markercluster/example/realworld.10000.js"></script>-->
	<script>

		if (localStorage.getItem("lastX") == null){
			// init variable/set default variable for item
			var lastX = 0;
		} else {
			var lastX = localStorage.getItem("lastX");
		}

		if (localStorage.getItem("lastY") == null){
			// init variable/set default variable for item
			var lastY = 0;
		} else {
			var lastY = localStorage.getItem("lastY");
		}

		var map = L.map('map', {
			crs: L.CRS.Simple,
		});

		var x1 = 0;
		//11765/100;
		var y1 = 0;
		//-10079/100;
		var x2 = 800;
		//-15891/100;
		var y2 = 800;
		//23282/100;
		
		var bounds = [[x1,y1], [x2, y2]];
		var image = L.imageOverlay('../static/images/floor_map.png').addTo(map);

		//map.setView([65.24751, 14.23828], 5);
		//var tiles = L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
		//	attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors',
		//}).addTo(map);

		// addressPoints = addressPoints.map(function (p) { return [p[0], p[1]]; });
		// console.log(addressPoints);
		// var heat = L.heatLayer(addressPoints).addTo(map);
		//map.fitBounds(bounds);
		//map.setMaxBounds(bounds)

		map.on('click', function(e){
			var coord = e.latlng;
			var lat = coord.lat;
			var lng = coord.lng;
			console.log("You clicked the map at latitude: " + lat + " and longitude: " + lng);
		});
		
		// image dims
		w = 841;
		h = 982;
		var mapWidth=map._container.offsetWidth;
		var mapHeight=map._container.offsetHeight;
		

		function update(){
			$.getJSON(
				"{% url 'base:update' %}",	
				{},
				function (data) {
					console.log(mapWidth)
					console.log(mapHeight)
					console.log(data); // This is the json object
					x = data[2]['Reidar']['coord']['x']
					y = data[2]['Reidar']['coord']['y']
					if (!((lastX == 0)&&(lastY==0))) {
						var sol =([((x - lastX)/11.33), ((y-lastY)/17.37)]);
						L.marker(sol).addTo(map);
						localStorage.setItem("lastX", x);
						localStorage.setItem("lastY", y);
					} 
				
					setTimeout(update, 1000);
				}
			)
		}
		$(document).ready(
			update
		);
		map.setView([0,0], 1);
																							
	</script>
</body>

</html>

16300, 403

senior_track/track/templates/track/index.html
{% load static %}
<!DOCTYPE html>
<html style="background-color: #ffffff;">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Home - Brand</title>
    <link rel="stylesheet" href="static/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic">
    <link rel="stylesheet" href="static/assets/fonts/font-awesome.min.css">
    <link rel="stylesheet" href="static/assets/fonts/simple-line-icons.min.css">
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Roboto:400,300,700,400italic,300italic,700italic">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href="static/assets/css/TR-Form.css">

    <script type="text/javascript" src="{% static 'js/jquery-3.3.1.js' %}"></script>

</head>

<body>

    <script>
        function update(){
            $.getJSON(
                "{% url 'base:update' %}",
                {},
                function (data) {
                    console.log(data); // This is the json object
                    setTimeout(update, 1000)
                }
            )
        }
        $(document).ready(
            update
        );
    </script>

    <nav class="navbar navbar-light navbar-expand bg-light navigation-clean">
        <div class="container"><a class="navbar-brand" href="#">Track an elderly person</a><button
                class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1"></button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav">
                    <li class="nav-item" role="presentation"><a class="nav-link active" href="{% url 'base:home' %}">Home</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="#addProfile">User profile</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href= "http://stapp.cloud.pozyxlabs.com">Map</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="#">Terms &amp; Use</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div  href ="#">
    <header class="masthead text-white text-center" style="background: url('static/images/floor_map.png')no-repeat center center;background-size: cover;height: 419px;"></header>
    </div>
    <section class="features-icons bg-light text-center" style="background-color: rgb(12,53,94);">
        <div class="container">
            <div class="row">
                <div class="col-lg-4">
                    <div class="mx-auto features-icons-item mb-5 mb-lg-0 mb-lg-3">
                        <div class="d-flex features-icons-icon"><i class="icon-screen-desktop m-auto text-primary"
                                data-bs-hover-animate="pulse"></i></div>
                        <h3>No Escape</h3>
                        <p class="lead mb-0">Did nan run away again? Worry not, we got you covered! Surveillance 24/7 makes sure we'll locate your nan in no time!</p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="mx-auto features-icons-item mb-5 mb-lg-0 mb-lg-3">
                        <div class="d-flex features-icons-icon"><i class="icon-layers m-auto text-primary" data-bs-hover-animate="pulse"></i></div>
                        <h3>Full building Coverage</h3>
                        <p class="lead mb-0">Large building ? No problem. <br>Anchors on every floor makes sure there are no nooks nor crannies left uncovered by our tracking</p>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="mx-auto features-icons-item mb-5 mb-lg-0 mb-lg-3">
                        <div class="d-flex features-icons-icon"><i class="icon-check m-auto text-primary" data-bs-hover-animate="pulse"></i></div>
                        <h3>Capture Guaranteed</h3>
                        <p class="lead mb-0"></p>
                    </div>
                    <p class="lead mb-0">Lost elderly are guaranteed to be returned within the hour<br><br></p>
                </div>
            </div>
            <div class="row" style="background-color: rgba(255,255,255,0);padding: 106px;">
                <div class="col">
                    <div class="card", id = "addProfile">
                        <div class="card-body mt-auto">
                            <h4 class="card-title">Add a Profile</h4>
                            <form class="register-form">
                                <fieldset>
                                    <div class="form-row">
                                        <div class="col-md-12"><input class="form-control d-none" type="text" value="vr-campus-tours" id="lp-formID"><input class="form-control d-none" type="text" value="<?php echo $_GET['path'];?>" id="lp-pathID"></div>
                                        <div class="col-12 col-sm-6 col-md-12">
                                            <div id="lp-name-wrapper"><input class="form-control" type="text" placeholder="Enter parameters" id="lp-name"></div>
                                        </div>
                                        <div class="col-12 col-sm-6 col-md-12">
                                            <div id="lp-mail-wrapper"><input class="form-control" type="text" placeholder="Enter parameters" id="lp-mail"></div>
                                        </div>
                                        <div class="col-12 col-sm-6 col-md-12">
                                            <div id="lp-telnumber-wrapper"><input class="form-control" type="text" placeholder="Enter parameters" id="lp-telnumber"></div>
                                        </div>
                                        <div class="col-12 col-sm-6 col-md-12">
                                            <div id="customfield1-wrapper"><input class="form-control" type="text" placeholder="Enter parameters"id="customfield1"></div>
                                        </div>
                                        <div class="col-12 col-sm-6 col-md-12">
                                            <div id="lp-title-wrapper"><input class="form-control" type="text" placeholder="Enter parameters" id="lp-title"></div>
                                        </div>
                                        <div class="col-12 col-sm-6 col-md-12">
                                            <div id="lp-check1-wrapper">
                                                <div class="form-check"><input class="form-check-input" type="checkbox" id="lp-check1"><label class="text" for="lp-check1">Are you sure the above information is correct?</label></div>
                                            </div>
                                        </div>
                                        <div class="col-md-12"><input class="form-control d-none" type="text"
                                                id="lp-country"><input class="form-control d-none" type="text"
                                                id="lp-website"><input class="form-control d-none" type="text"
                                                id="lp-city"><input class="form-control d-none" type="text"
                                                id="customfield10"><input class="form-control d-none" type="text"
                                                id="customfield9"><input class="form-control d-none" type="text"
                                                id="customfield8"><input class="form-control d-none" type="text"
                                                id="customfield7"><input class="form-control d-none" type="text"
                                                id="customfield6"><input class="form-control d-none" type="text"
                                                id="customfield5"><input class="form-control d-none" type="text"
                                                id="customfield4">
                                            <input class="form-control d-none" type="text" id="customfield3"><input
                                                class="form-control d-none" type="text" id="customfield2"><input
                                                class="form-control d-none" type="text" id="lp-select3"><input
                                                class="form-control d-none" type="text" id="lp-select2"><input
                                                class="form-control d-none" type="text" id="lp-check5"><input
                                                class="form-control d-none" type="text" id="lp-check4"><input
                                                class="form-control d-none" type="text" id="lp-check3"><input
                                                class="form-control d-none" type="text" id="lp-check2">
                                            <input class="form-control d-none" type="text" id="lp-telareacode"><input
                                                class="form-control d-none" type="text" id="lp-telcountrycode"></div>
                                        <div class="col-12 col-sm-12 col-md-12"><button class="btn btn-outline-primary"
                                                type="button" style="width: 173px;">Create Profile</button></div>
                                        <div class="col-md-12">
                                            <div class="push-50"></div>
                                        </div>
                                    </div>
                                </fieldset>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">List of Profiles</h4>
                            <ul class="list-group">
                                <li class="list-group-item"><span>Disabled</span></li>
                                <li class="list-group-item"><span>Forgetful</span></li>
                                <li class="list-group-item"><span>Dangerous</span></li>
                                <li class="list-group-item"><span>Contagious</span></li>
                                <li class="list-group-item"><span>Healthy</span></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="showcase"></section>
    <footer class="footer bg-light">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 my-auto h-100 text-center text-lg-left">
                    <ul class="list-inline mb-2">
                        <li class="list-inline-item"><a href="#">About</a></li>
                        <li class="list-inline-item"><span>⋅</span></li>
                        <li class="list-inline-item"><a href="#">Contact</a></li>
                        <li class="list-inline-item"><span>⋅</span></li>
                        <li class="list-inline-item"><a href="#">Terms of &nbsp;Use</a></li>
                        <li class="list-inline-item"><span>⋅</span></li>
                        <li class="list-inline-item"><a href="#">Privacy Policy</a></li>
                    </ul>
                    <p class="text-muted small mb-4 mb-lg-0">© Brand 2018. All Rights Reserved.</p>
                </div>
                <div class="col-lg-6 my-auto h-100 text-center text-lg-right">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item"><a href="#"><i class="fa fa-facebook fa-2x fa-fw"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fa fa-twitter fa-2x fa-fw"></i></a></li>
                        <li class="list-inline-item"><a href="#"><i class="fa fa-instagram fa-2x fa-fw"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="assets/js/bs-animation.js"></script>
</body>

</html>